// 导入所有 CSS 文件
import './css/address.scss'
import './css/author.scss'
import './css/bind_weixin.scss'
import './css/center.scss'
import './css/config.scss'
import './css/orders.scss'
import './css/score.scss'
import './css/uploadavatar.scss'
import './css/vip.scss'
