<?php
/**
 * +----------------------------------------------------------------------
 *                                  |
 *     __     __  __     __  __     | FILE: Payment.php
 *    /\ \   /\_\_\_\   /\_\_\_\    | AUTHOR: 季骁宣
 *   _\_\ \  \/_/\_\/_  \/_/\_\/_   | EMAIL: jxx0410@sina.com
 *  /\_____\   /\_\/\_\   /\_\/\_\  | QQ: 516036855
 *  \/_____/   \/_/\/_/   \/_/\/_/  | DATETIME: 2021/11/2
 *                                  |-------------------------------------
 *                                  | 登山则情满于山,观海则意溢于海
 * +----------------------------------------------------------------------
 */
namespace app\unions\controller\service;
use app\common\controller\Base;
use app\common\model\CapitalFlow;
use app\common\model\Member;
use app\unions\model\MiniProgramConfig;
use app\unions\model\WechatConfig;
use think\Exception;
use think\facade\Db;

class Payment extends Base {
    private $className = [
         1 => 'WehcatPayment',
         2 => 'WehcatPayment',
         3 => 'AlipayPayment',
    ];
    private $payService;//支付服务
    private $orderService;//订单服务
    private $module;//模块名称
    private $shopid;//店铺ID
    private $params;//参数
    function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //参数赋值
        $this->params = input('param.');
        $pay_type = $this->params['pay_type'] ?? 1;
        $shopid = $this->shopid = $this->shopid ?? 0;
        $module = $this->module = $this->params['m'] ?? '';
        //获取appid
        $config = $this->getConfig($shopid ,$module ,$pay_type);
        //获取实例化的服务
        $pay_namespace = "app\\unions\\service\\pay\\{$this->className[$pay_type]}Payment";
        $this->payService = new $pay_namespace($config['appid']);

        $order_namespace = "app\\{$module}\\api\\Order";
        $this->orderService = new $order_namespace;
    }

    /**
     * 下单
     * @param $order_data
     */
    function createOrder(){
        if (request()->isAjax()){
            Db::startTrans();
            try {
                //具体业务 分发到相应程序订单类
                $order = $this->orderService->createOrder($this->params);
                if ($order){
                    $result = $this->payService->pay($order);
                }
                Db::commit();
                $this->success('创建订单成功',$result);
            }catch (\Exception $e){
                Db::rollback();
                $this->error($e->getMessage());
            }
        }
    }

    /**
     * 退款
     */
    function refund(){
        if (request()->isAjax()){
            //开启事务
            Db::startTrans();
            try {
                //处理订单业务
                $order = $this->orderService->refund($this->params);
                if (!$order){
                    throw new Exception('订单不存在');
                }
                //生成订单流水
                $this->createCapitalFlow($order);
                //退款逻辑
                if ($this->params['refund_to'] == 0){
                    //退款至用户账户
                    $result = Member::updateAmount($order['uid'],'balance',$order['price']);
                }elseif($this->params['refund_to'] == 1){
                    //退款至付款账户
                    $result = $this->payService->refund($order);
                    if ($result['return_code'] == 'SUCCESS' && $result['result_code'] == 'SUCCESS'){
                        $result = true;
                    }else{
                        throw new Exception($result['return_code']);
                    }
                }
                if (!$result){
                    throw new Exception('网络异常，请稍后再试');
                }
                Db::commit();
                $this->success('退款成功');
            }catch (\Exception $e){
                Db::rollback();
                $this->error($e->getMessage());
            }
        }
    }

    /**
     * 支付成功回调
     *
     */
    function payCallback(){
        $notify_xml = file_get_contents("php://input");
        $jsonxml = json_encode(simplexml_load_string($notify_xml, 'SimpleXMLElement', LIBXML_NOCDATA));
        $notify = json_decode($jsonxml, true);
        //判断订单是否已支付
        $result = $this->payService->notify($notify);
        if ($result){//true未支付
            $this->orderService->notify($notify['out_trade_no']);
            //消息通知
        }
        $this->success('回调成功');
    }

    function createCapitalFlow($data){
        //生成订单流水
        $flow_data = [
            'shopid'    => $this->shopid,
            'uid'       => $data['uid'],
            'flow_no'   => $data['refund_no'] ?? CapitalFlow::build_flow_no(),
            'order_no'  => $data['order_no'],
            'channel'   => ($this->params['refund_to'] ?? 0) > 0 ? $data['channel'] : 0,
            'type'      => 1,
            'price'     => $data['price'],
            'remark'    => $data['remark'] ?? '',
            'status'    => $data['status'] ?? 1
        ];
        $flow_res = (new CapitalFlow())->edit($flow_data);
        if (!$flow_res){
            throw new Exception('生成流水号失败');
        }
    }

    /**
     * 获取配置信息
     * @param $shopid
     * @param string $module
     * @param int $type
     * @return MiniProgramConfig|WechatConfig|array|\think\Model
     * @throws Exception
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\DbException
     * @throws \think\db\exception\ModelNotFoundException
     */
    protected function getConfig($shopid ,$module = '',$type = 1)
    {
        switch ($type){
            //微信公众号
            case 1:
                $data = (new WechatConfig())->getWechatConfigByShopId($shopid);
                if (empty($data)){
                    throw  new Exception('公众号配置文件不存在');
                }
                break;
            //微信小程序
            case 2:
                //获取配置信息
                $map = [
                    ['shopid' ,'=' ,$shopid],
                    ['name' ,'=' , $module],
                    ['platform' ,'=' ,'wechat']
                ];
                $data = (new MiniProgramConfig())->where($map)->find();
                if (empty($data)){
                    throw  new Exception('小程序配置信息不存在');
                }
                break;
        }
        return $data;
    }
}